project_name: loxa-go
version: 0.1.0
archives:
  - format: tar.gz
builds:
  - id: loxa-collector
    dir: ./cmd/loxa-collector
    binary: loxa-collector
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: loxa-worker
    dir: ./cmd/loxa-worker
    binary: loxa-worker
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: loxa
    dir: ./cmd/loxa
    binary: loxa
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: loxa-loadgen
    dir: ./cmd/loxa-loadgen
    binary: loxa-loadgen
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image: astraive/loxa-collector
    dockerfile: build/Dockerfile.collector
    goos: linux
    goarch:
      - amd64
      - arm64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^refactor:'
release:
  github:
    owner: Astraive
    name: loxa-go
  draft: true