package metrics

const (
	RequestsTotalName      = "loxa_collector_requests_total"
	RequestsAuthErrorsName = "loxa_collector_requests_auth_errors_total"
	RequestsLimitedName    = "loxa_collector_requests_limited_total"
	RequestsThrottledName  = "loxa_collector_requests_throttled_total"
	EventsAcceptedName     = "loxa_collector_events_accepted_total"
	EventsInvalidName      = "loxa_collector_events_invalid_total"
	EventsRejectedName     = "loxa_collector_events_rejected_total"
	EventsDedupedName      = "loxa_collector_events_deduped_total"
	SinkWriteErrorsName    = "loxa_collector_sink_write_errors_total"
	DiskFullErrorsName     = "loxa_collector_disk_full_errors_total"
	ParseErrorsName        = "loxa_collector_parse_errors_total"
	SpoolBytesName         = "loxa_collector_spool_bytes"
	QueueBytesName         = "loxa_collector_queue_bytes"
	InflightRequestsName   = "loxa_collector_inflight_requests"
	InflightEventsName     = "loxa_collector_inflight_events"
	SinkHealthName         = "loxa_collector_sink_health"
	DiskHealthName         = "loxa_collector_disk_health"
	SpoolHealthName        = "loxa_collector_spool_health"
	ReadyName              = "loxa_collector_ready"
	SchemaValidationsName  = "loxa_collector_schema_validations_total"
	SchemaWarningsName     = "loxa_collector_schema_warnings_total"
	SchemaRejectionsName   = "loxa_collector_schema_rejections_total"
	DLQWritesName          = "loxa_collector_dlq_writes_total"
	DLQWriteFailuresName   = "loxa_collector_dlq_write_failures_total"
	QuarantineWritesName   = "loxa_collector_quarantine_writes_total"
	RetryAttemptsName      = "loxa_collector_retry_attempts_total"
	RetrySuccessesName     = "loxa_collector_retry_successes_total"
	RetryFailuresName      = "loxa_collector_retry_failures_total"
)
